//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvDT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvDT.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Condition.json.
        /// </summary>
        internal static string conditionJson {
            get {
                return ResourceManager.GetString("conditionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Country.json.
        /// </summary>
        internal static string countryJson {
            get {
                return ResourceManager.GetString("countryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Laboratory.json.
        /// </summary>
        internal static string laboratoryJson {
            get {
                return ResourceManager.GetString("laboratoryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Medium.json.
        /// </summary>
        internal static string mediumJson {
            get {
                return ResourceManager.GetString("mediumJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/MediumSubType.json.
        /// </summary>
        internal static string mediumSubTypeJson {
            get {
                return ResourceManager.GetString("mediumSubTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Parameter.json.
        /// </summary>
        internal static string parameterJson {
            get {
                return ResourceManager.GetString("parameterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/ParameterLaboratory.json.
        /// </summary>
        internal static string parameterLaboratoryJson {
            get {
                return ResourceManager.GetString("parameterLaboratoryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/PublCountry.json.
        /// </summary>
        internal static string publCountryJson {
            get {
                return ResourceManager.GetString("publCountryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Publication.json.
        /// </summary>
        internal static string publicationJson {
            get {
                return ResourceManager.GetString("publicationJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/PublRegion.json.
        /// </summary>
        internal static string publRegionJson {
            get {
                return ResourceManager.GetString("publRegionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/RefValue.json.
        /// </summary>
        internal static string refValueJson {
            get {
                return ResourceManager.GetString("refValueJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Region.json.
        /// </summary>
        internal static string regionJson {
            get {
                return ResourceManager.GetString("regionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Unit.json.
        /// </summary>
        internal static string unitJson {
            get {
                return ResourceManager.GetString("unitJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/ValuationClassCondition.json.
        /// </summary>
        internal static string valuationClassConditionJson {
            get {
                return ResourceManager.GetString("valuationClassConditionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/ValuationClass.json.
        /// </summary>
        internal static string valuationClassJson {
            get {
                return ResourceManager.GetString("valuationClassJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/ValuationClassMedSubType.json.
        /// </summary>
        internal static string valuationClassMedSubTypeJson {
            get {
                return ResourceManager.GetString("valuationClassMedSubTypeJson", resourceCulture);
            }
        }
    }
}
