//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvDT.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvDT.Model.DbResources", typeof(DbResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Condition.json.
        /// </summary>
        internal static string conditionJson {
            get {
                return ResourceManager.GetString("conditionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/ConfigCsv.json.
        /// </summary>
        internal static string configCsvJson {
            get {
                return ResourceManager.GetString("configCsvJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/ConfigXlsx.json.
        /// </summary>
        internal static string configXlsxJson {
            get {
                return ResourceManager.GetString("configXlsxJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Country.json.
        /// </summary>
        internal static string countryJson {
            get {
                return ResourceManager.GetString("countryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Laboratory.json.
        /// </summary>
        internal static string laboratoryJson {
            get {
                return ResourceManager.GetString("laboratoryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Language.json.
        /// </summary>
        internal static string languageJson {
            get {
                return ResourceManager.GetString("languageJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Medium.json.
        /// </summary>
        internal static string mediumJson {
            get {
                return ResourceManager.GetString("mediumJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/MediumSubType.json.
        /// </summary>
        internal static string mediumSubTypeJson {
            get {
                return ResourceManager.GetString("mediumSubTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Parameter.json.
        /// </summary>
        internal static string parameterJson {
            get {
                return ResourceManager.GetString("parameterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/ParamNameVariant.json.
        /// </summary>
        internal static string paramNameVariantJson {
            get {
                return ResourceManager.GetString("paramNameVariantJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Project.json.
        /// </summary>
        internal static string projectJson {
            get {
                return ResourceManager.GetString("projectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/PublCountry.json.
        /// </summary>
        internal static string publCountryJson {
            get {
                return ResourceManager.GetString("publCountryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Publication.json.
        /// </summary>
        internal static string publicationJson {
            get {
                return ResourceManager.GetString("publicationJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/PublParam.json.
        /// </summary>
        internal static string publParamJson {
            get {
                return ResourceManager.GetString("publParamJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/PublRegion.json.
        /// </summary>
        internal static string publRegionJson {
            get {
                return ResourceManager.GetString("publRegionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/RefValue.json.
        /// </summary>
        internal static string refValueJson {
            get {
                return ResourceManager.GetString("refValueJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Region.json.
        /// </summary>
        internal static string regionJson {
            get {
                return ResourceManager.GetString("regionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/Unit.json.
        /// </summary>
        internal static string unitJson {
            get {
                return ResourceManager.GetString("unitJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/unitNameVariant.json.
        /// </summary>
        internal static string unitNameVariantJson {
            get {
                return ResourceManager.GetString("unitNameVariantJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/ValuationClassCondition.json.
        /// </summary>
        internal static string valuationClassConditionJson {
            get {
                return ResourceManager.GetString("valuationClassConditionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/ValuationClass.json.
        /// </summary>
        internal static string valuationClassJson {
            get {
                return ResourceManager.GetString("valuationClassJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../EnvDT.DataAccess/DbDataSeeds/ValuationClassMedSubType.json.
        /// </summary>
        internal static string valuationClassMedSubTypeJson {
            get {
                return ResourceManager.GetString("valuationClassMedSubTypeJson", resourceCulture);
            }
        }
    }
}
