//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvDT.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvDT.UI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv-Configurator.
        /// </summary>
        public static string ConfigCsvDetailView_Label_Title {
            get {
                return ResourceManager.GetString("ConfigCsvDetailView_Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col..
        /// </summary>
        public static string ConfigDetailView_Label_Col {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator:.
        /// </summary>
        public static string ConfigDetailView_Label_DecimalSepChar {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_DecimalSepChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value delimiter:.
        /// </summary>
        public static string ConfigDetailView_Label_DelimiterChar {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_DelimiterChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection limit column:.
        /// </summary>
        public static string ConfigDetailView_Label_DetectionLimitCol {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_DetectionLimitCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First data row:.
        /// </summary>
        public static string ConfigDetailView_Label_FirstDataRow {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_FirstDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First column with sample value:.
        /// </summary>
        public static string ConfigDetailView_Label_FirstSampleValueCol {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_FirstSampleValueCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header row:.
        /// </summary>
        public static string ConfigDetailView_Label_HeaderRow {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_HeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification word:.
        /// </summary>
        public static string ConfigDetailView_Label_IdentWord {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_IdentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification word cell:.
        /// </summary>
        public static string ConfigDetailView_Label_IdentWordCell {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_IdentWordCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification word row:.
        /// </summary>
        public static string ConfigDetailView_Label_IdentWordRow {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_IdentWordRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method column:.
        /// </summary>
        public static string ConfigDetailView_Label_MethodCol {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_MethodCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name column:.
        /// </summary>
        public static string ConfigDetailView_Label_ParamNameCol {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_ParamNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell of Report-Identifier:.
        /// </summary>
        public static string ConfigDetailView_Label_ReportLabidentCell {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_ReportLabidentCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string ConfigDetailView_Label_Row {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of sample lab-identifiers:.
        /// </summary>
        public static string ConfigDetailView_Label_SampleLabIdentRow {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_SampleLabIdentRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of sample names:.
        /// </summary>
        public static string ConfigDetailView_Label_SampleNameRow {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_SampleNameRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name column:.
        /// </summary>
        public static string ConfigDetailView_Label_UnitNameCol {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_UnitNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet name:.
        /// </summary>
        public static string ConfigDetailView_Label_WorksheetName {
            get {
                return ResourceManager.GetString("ConfigDetailView_Label_WorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this configuration?.
        /// </summary>
        public static string ConfigDetailVM_DialogMsg_ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfigDetailVM_DialogMsg_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Xlsx-Configuration.
        /// </summary>
        public static string ConfigDetailVM_DialogTitle_ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfigDetailVM_DialogTitle_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xls(x)-Configurator.
        /// </summary>
        public static string ConfigXlsxDetailView_Label_Title {
            get {
                return ResourceManager.GetString("ConfigXlsxDetailView_Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following values are not in a correct number format: {0}.
        /// </summary>
        public static string DialogMsg_FormatError {
            get {
                return ResourceManager.GetString("DialogMsg_FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Error.
        /// </summary>
        public static string DialogTitle_FormatError {
            get {
                return ResourceManager.GetString("DialogTitle_FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the following key could not be read: {0}..
        /// </summary>
        public static string ImportLabReportService_DialogMsg_CellError {
            get {
                return ResourceManager.GetString("ImportLabReportService_DialogMsg_CellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This LabReport has already been imported. Please chose another file or delete the LabReport first..
        /// </summary>
        public static string ImportLabReportService_DialogMsg_ImportLabReport {
            get {
                return ResourceManager.GetString("ImportLabReportService_DialogMsg_ImportLabReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table cell value error.
        /// </summary>
        public static string ImportLabReportService_DialogTitle_CellError {
            get {
                return ResourceManager.GetString("ImportLabReportService_DialogTitle_CellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import LabReport.
        /// </summary>
        public static string ImportLabReportService_DialogTitle_ImportLabReport {
            get {
                return ResourceManager.GetString("ImportLabReportService_DialogTitle_ImportLabReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is experimental.
        ///
        ///UNLESS OTHERWISE MUTUALLY AGREED TO BY THE PARTIES IN WRITING, 
        ///LICENSOR OFFERS THE WORK AS-IS AND MAKES NO REPRESENTATIONS 
        ///OR WARRANTIES OF ANY KIND CONCERNING THE WORK, EXPRESS, 
        ///IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, 
        ///WARRANTIES OF TITLE, MERCHANTIBILITY, FITNESS FOR A PARTICULAR 
        ///PURPOSE, NONINFRINGEMENT, OR THE ABSENCE OF LATENT OR OTHER 
        ///DEFECTS, ACCURACY, OR THE PRESENCE OF ABSENCE OF ERRORS, 
        ///WHETHER OR NOT DISCOVERABLE. SOME JURISDIC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoDetailView_Label_Disclaimer {
            get {
                return ResourceManager.GetString("InfoDetailView_Label_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2021 Daniel Oellers.
        /// </summary>
        public static string InfoDetailView_Label_Info {
            get {
                return ResourceManager.GetString("InfoDetailView_Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string InfoDetailView_Label_License {
            get {
                return ResourceManager.GetString("InfoDetailView_Label_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version/Build:.
        /// </summary>
        public static string InfoDetailView_Label_Version {
            get {
                return ResourceManager.GetString("InfoDetailView_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv-Config..
        /// </summary>
        public static string LabDetailView_Button_NewCsvConfig {
            get {
                return ResourceManager.GetString("LabDetailView_Button_NewCsvConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xls(x)-Config..
        /// </summary>
        public static string LabDetailView_Button_NewXlsxConfig {
            get {
                return ResourceManager.GetString("LabDetailView_Button_NewXlsxConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string LabDetailView_Label_Country {
            get {
                return ResourceManager.GetString("LabDetailView_Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory company.
        /// </summary>
        public static string LabDetailView_Label_LabCompany {
            get {
                return ResourceManager.GetString("LabDetailView_Label_LabCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory name.
        /// </summary>
        public static string LabDetailView_Label_LabName {
            get {
                return ResourceManager.GetString("LabDetailView_Label_LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the laboratory {0} {1}?.
        /// </summary>
        public static string LabDetailVM_DialogMsg_ConfirmDeletion {
            get {
                return ResourceManager.GetString("LabDetailVM_DialogMsg_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete laboratory.
        /// </summary>
        public static string LabDetailVM_DialogTitle_ConfirmDeletion {
            get {
                return ResourceManager.GetString("LabDetailVM_DialogTitle_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameters.
        /// </summary>
        public static string LabReportPreCheck_DialogTitle_MissingParam {
            get {
                return ResourceManager.GetString("LabReportPreCheck_DialogTitle_MissingParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string LabReportView_Button_Eval {
            get {
                return ResourceManager.GetString("LabReportView_Button_Eval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Report.
        /// </summary>
        public static string LabReportView_Button_Import {
            get {
                return ResourceManager.GetString("LabReportView_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string LabReportView_Button_Open {
            get {
                return ResourceManager.GetString("LabReportView_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabReports.
        /// </summary>
        public static string LabReportView_GridHeader_LabReports {
            get {
                return ResourceManager.GetString("LabReportView_GridHeader_LabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import of laboratory report.
        /// </summary>
        public static string LabReportView_TextBlock_LoadingPopup {
            get {
                return ResourceManager.GetString("LabReportView_TextBlock_LoadingPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close first related open Tab {0}..
        /// </summary>
        public static string LabReportVM_DialogMsg_CloseTab {
            get {
                return ResourceManager.GetString("LabReportVM_DialogMsg_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the LabReport {0} and all related samples and values?.
        /// </summary>
        public static string LabReportVM_DialogMsg_ConfirmDeletion {
            get {
                return ResourceManager.GetString("LabReportVM_DialogMsg_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete LabReport.
        /// </summary>
        public static string LabReportVM_DialogTitle_CloseTab {
            get {
                return ResourceManager.GetString("LabReportVM_DialogTitle_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete LabReport.
        /// </summary>
        public static string LabReportVM_DialogTitle_ConfirmDeletion {
            get {
                return ResourceManager.GetString("LabReportVM_DialogTitle_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory selection.
        /// </summary>
        public static string LabView_Label_LabSelection {
            get {
                return ResourceManager.GetString("LabView_Label_LabSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MainTabView_Header_Title {
            get {
                return ResourceManager.GetString("MainTabView_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string MainWindow_Header_Info {
            get {
                return ResourceManager.GetString("MainWindow_Header_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab-Configurator.
        /// </summary>
        public static string MainWindow_Header_LabConfig {
            get {
                return ResourceManager.GetString("MainWindow_Header_LabConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Header_Main {
            get {
                return ResourceManager.GetString("MainWindow_Header_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Header_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MissingParamDialog_GridHeader_Language {
            get {
                return ResourceManager.GetString("MissingParamDialog_GridHeader_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string MissingParamDialog_GridHeader_Parameter {
            get {
                return ResourceManager.GetString("MissingParamDialog_GridHeader_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Alias.
        /// </summary>
        public static string MissingParamDialog_GridHeader_SelectedParamAlias {
            get {
                return ResourceManager.GetString("MissingParamDialog_GridHeader_SelectedParamAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Alias.
        /// </summary>
        public static string MissingParamDialog_GridHeader_SelectedUnitAlias {
            get {
                return ResourceManager.GetString("MissingParamDialog_GridHeader_SelectedUnitAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string MissingParamDialog_GridHeader_Unit {
            get {
                return ResourceManager.GetString("MissingParamDialog_GridHeader_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameters:.
        /// </summary>
        public static string MissingParamDialog_Label_MissingParams {
            get {
                return ResourceManager.GetString("MissingParamDialog_Label_MissingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing units:.
        /// </summary>
        public static string MissingParamDialog_Label_MissingUnits {
            get {
                return ResourceManager.GetString("MissingParamDialog_Label_MissingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parameters could not be automatically identified. Please select 
        ///for each item a corresponding parameter name from the dropdown menu.
        ///If there is no corresponding parameter name or in the case of doubt, please select [N/A]..
        /// </summary>
        public static string MissingParamDialog_TextBlock_SelectParams {
            get {
                return ResourceManager.GetString("MissingParamDialog_TextBlock_SelectParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ProjectDetailView_Label_Country {
            get {
                return ResourceManager.GetString("ProjectDetailView_Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project address.
        /// </summary>
        public static string ProjectDetailView_Label_ProjectAddress {
            get {
                return ResourceManager.GetString("ProjectDetailView_Label_ProjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project client.
        /// </summary>
        public static string ProjectDetailView_Label_ProjectClient {
            get {
                return ResourceManager.GetString("ProjectDetailView_Label_ProjectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectDetailView_Label_ProjectName {
            get {
                return ResourceManager.GetString("ProjectDetailView_Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number.
        /// </summary>
        public static string ProjectDetailView_Label_ProjectNumber {
            get {
                return ResourceManager.GetString("ProjectDetailView_Label_ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string ProjectDetailView_Label_Region {
            get {
                return ResourceManager.GetString("ProjectDetailView_Label_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the project {0} {1}?.
        /// </summary>
        public static string ProjectDetailVM_DialogMsg_ConfirmDeletion {
            get {
                return ResourceManager.GetString("ProjectDetailVM_DialogMsg_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close first all open Tabs..
        /// </summary>
        public static string ProjectDetailVM_DialogMsg_DeleteCloseTabs {
            get {
                return ResourceManager.GetString("ProjectDetailVM_DialogMsg_DeleteCloseTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Project.
        /// </summary>
        public static string ProjectDetailVM_DialogTitle_ConfirmDeletion {
            get {
                return ResourceManager.GetString("ProjectDetailVM_DialogTitle_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Project.
        /// </summary>
        public static string ProjectDetailVM_DialogTitle_DeleteCloseTabs {
            get {
                return ResourceManager.GetString("ProjectDetailVM_DialogTitle_DeleteCloseTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project....
        /// </summary>
        public static string ProjectView_Button_AddProject {
            get {
                return ResourceManager.GetString("ProjectView_Button_AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project selection.
        /// </summary>
        public static string ProjectView_Label_ProjectSelection {
            get {
                return ResourceManager.GetString("ProjectView_Label_ProjectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Excel file is probably corrupt. Please save the file again in Excel by overwriting the same file. Details: {0}.
        /// </summary>
        public static string ReadFileHelper_DialogMsg_CorruptExcel {
            get {
                return ResourceManager.GetString("ReadFileHelper_DialogMsg_CorruptExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Details: {0}.
        /// </summary>
        public static string ReadFileHelper_DialogMsg_FileError {
            get {
                return ResourceManager.GetString("ReadFileHelper_DialogMsg_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The laboratory could not be identified. Please check the LabReport configurator settings or add a new configuration..
        /// </summary>
        public static string ReadFileHelper_DialogMsg_UnknLabRFormat {
            get {
                return ResourceManager.GetString("ReadFileHelper_DialogMsg_UnknLabRFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt Excel file.
        /// </summary>
        public static string ReadFileHelper_DialogTitle_CorruptExcel {
            get {
                return ResourceManager.GetString("ReadFileHelper_DialogTitle_CorruptExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File error.
        /// </summary>
        public static string ReadFileHelper_DialogTitle_FileError {
            get {
                return ResourceManager.GetString("ReadFileHelper_DialogTitle_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown LabReport format.
        /// </summary>
        public static string ReadFileHelper_DialogTitle_UnknLabRFormat {
            get {
                return ResourceManager.GetString("ReadFileHelper_DialogTitle_UnknLabRFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SampleDetailView_Button_Copy {
            get {
                return ResourceManager.GetString("SampleDetailView_Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit samples.
        /// </summary>
        public static string SampleDetailView_Button_Edit {
            get {
                return ResourceManager.GetString("SampleDetailView_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string SampleDetailView_Button_Eval {
            get {
                return ResourceManager.GetString("SampleDetailView_Button_Eval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate footnotes
        ///(experimental, uncomplete).
        /// </summary>
        public static string SampleDetailView_Checkbox_EvalFootnotes {
            get {
                return ResourceManager.GetString("SampleDetailView_Checkbox_EvalFootnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi. methods conflicts.
        /// </summary>
        public static string SampleDetailView_Label_DiffLrParam {
            get {
                return ResourceManager.GetString("SampleDetailView_Label_DiffLrParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi. values conflict.
        /// </summary>
        public static string SampleDetailView_Label_SameLrParam {
            get {
                return ResourceManager.GetString("SampleDetailView_Label_SameLrParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. value.
        /// </summary>
        public static string SampleDetailView_RadioButton_MaxValue {
            get {
                return ResourceManager.GetString("SampleDetailView_RadioButton_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. value.
        /// </summary>
        public static string SampleDetailView_RadioButton_MinValue {
            get {
                return ResourceManager.GetString("SampleDetailView_RadioButton_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string SampleDetailView_ToolTip_CopyButton {
            get {
                return ResourceManager.GetString("SampleDetailView_ToolTip_CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines which analytical value is selected if multiple values were found for the same parameter using different analytical methods..
        /// </summary>
        public static string SampleDetailView_ToolTip_DiffLrParam {
            get {
                return ResourceManager.GetString("SampleDetailView_ToolTip_DiffLrParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines which analytical value is selected if multiple values were found for the same parameter - e.g. from different fractions of the same sample..
        /// </summary>
        public static string SampleDetailView_ToolTip_SameLrParam {
            get {
                return ResourceManager.GetString("SampleDetailView_ToolTip_SameLrParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit samples.
        /// </summary>
        public static string SampleDetailVM_DialogTitle_EditSamples {
            get {
                return ResourceManager.GetString("SampleDetailVM_DialogTitle_EditSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken into account: .
        /// </summary>
        public static string SampleDetailVM_Footnote_MinParams {
            get {
                return ResourceManager.GetString("SampleDetailVM_Footnote_MinParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing:.
        /// </summary>
        public static string SampleDetailVM_Footnote_Missing {
            get {
                return ResourceManager.GetString("SampleDetailVM_Footnote_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking account of: .
        /// </summary>
        public static string SampleDetailVM_Footnote_TakingAccountOf {
            get {
                return ResourceManager.GetString("SampleDetailVM_Footnote_TakingAccountOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the following parameters, tolerance values as defined in [{0}] were applied:.
        /// </summary>
        public static string SampleDetailVM_Footnote_ToleranceParams {
            get {
                return ResourceManager.GetString("SampleDetailVM_Footnote_ToleranceParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifi-
        ///cation..
        /// </summary>
        public static string SampleDetailVM_GridHeader_Classification {
            get {
                return ResourceManager.GetString("SampleDetailVM_GridHeader_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classif.
        ///Params..
        /// </summary>
        public static string SampleDetailVM_GridHeader_ClassificationParams {
            get {
                return ResourceManager.GetString("SampleDetailVM_GridHeader_ClassificationParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string SampleDetailVM_GridHeader_Sample {
            get {
                return ResourceManager.GetString("SampleDetailVM_GridHeader_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Code.
        /// </summary>
        public static string SampleDetailVM_GridHeader_WasteCode {
            get {
                return ResourceManager.GetString("SampleDetailVM_GridHeader_WasteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string SampleEditDialog_GridHeader_Condition {
            get {
                return ResourceManager.GetString("SampleEditDialog_GridHeader_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string SampleEditDialog_GridHeader_Sample {
            get {
                return ResourceManager.GetString("SampleEditDialog_GridHeader_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Code.
        /// </summary>
        public static string SampleEditDialog_GridHeader_WasteCode {
            get {
                return ResourceManager.GetString("SampleEditDialog_GridHeader_WasteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the samples:.
        /// </summary>
        public static string SampleEditDialog_Label_EditSamples {
            get {
                return ResourceManager.GetString("SampleEditDialog_Label_EditSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsDetailView_Label_Language {
            get {
                return ResourceManager.GetString("SettingsDetailView_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UI_Button_Cancel {
            get {
                return ResourceManager.GetString("UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UI_Button_Delete {
            get {
                return ResourceManager.GetString("UI_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ....
        /// </summary>
        public static string UI_Button_New {
            get {
                return ResourceManager.GetString("UI_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string UI_Button_No {
            get {
                return ResourceManager.GetString("UI_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string UI_Button_OK {
            get {
                return ResourceManager.GetString("UI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string UI_Button_Save {
            get {
                return ResourceManager.GetString("UI_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string UI_Button_Yes {
            get {
                return ResourceManager.GetString("UI_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve made changes. Navigate away?.
        /// </summary>
        public static string VM_DialogMsg_ConfirmNavigate {
            get {
                return ResourceManager.GetString("VM_DialogMsg_ConfirmNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report the following error to your Administrator: {0}..
        /// </summary>
        public static string VM_DialogMsg_Error {
            get {
                return ResourceManager.GetString("VM_DialogMsg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Column or Row regarding {0} is out of range. Please check the lab-configuration. Details: {1}..
        /// </summary>
        public static string VM_DialogMsg_OutOfRangeEx {
            get {
                return ResourceManager.GetString("VM_DialogMsg_OutOfRangeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string VM_DialogTitle_ConfirmNavigate {
            get {
                return ResourceManager.GetString("VM_DialogTitle_ConfirmNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string VM_DialogTitle_Error {
            get {
                return ResourceManager.GetString("VM_DialogTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string VM_DialogTitle_OutOfRangeEx {
            get {
                return ResourceManager.GetString("VM_DialogTitle_OutOfRangeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty..
        /// </summary>
        public static string Wrapper_TextBlock_ValidationText {
            get {
                return ResourceManager.GetString("Wrapper_TextBlock_ValidationText", resourceCulture);
            }
        }
    }
}
